"""Typed specifications for model-pruning NAS APIs."""

from QEfficient.model_pruning.qeff_model_optimizer.config.artifacts import AppliedTransformRecord, ModelArtifact
from QEfficient.model_pruning.qeff_model_optimizer.config.eval import EvalSpec, QEffCompileSpec
from QEfficient.model_pruning.qeff_model_optimizer.config.models import ModelSpec
from QEfficient.model_pruning.qeff_model_optimizer.config.transforms import (
    CascadedCompensationConfig,
    CompensationLayerRatio,
    CompensationSpec,
    HeadPruningSpec,
    KvCacheCompressionSpec,
    LastTokenCompensationConfig,
    LayerHeadSelection,
    LearnableCompensationConfig,
    LinearAttentionSpec,
    MagnitudePreservingCompensationConfig,
    MagnitudeRescalingCompensationConfig,
    MlpPruningSpec,
    MultiClusterPhaseAwareMagnitudeRescalingCompensationConfig,
    MultiplicativeCompensationConfig,
    PcaCompensationConfig,
    PhaseAwareCompensationConfig,
    PhaseAwareLastTokenCompensationConfig,
    PhaseAwareMagnitudeRescalingCompensationConfig,
    PositionAwareCompensationConfig,
    RemoveLayersSpec,
    ScaledCompensationConfig,
    SkipLayersSpec,
    StructuredSparsitySpec,
    TransformationPlan,
    plan_from_dict,
    plan_to_dict,
    transform_spec_from_dict,
    transform_spec_to_dict,
)

__all__ = [
    "AppliedTransformRecord",
    "CascadedCompensationConfig",
    "CompensationLayerRatio",
    "CompensationSpec",
    "EvalSpec",
    "HeadPruningSpec",
    "KvCacheCompressionSpec",
    "LastTokenCompensationConfig",
    "LayerHeadSelection",
    "LearnableCompensationConfig",
    "LinearAttentionSpec",
    "MagnitudePreservingCompensationConfig",
    "MagnitudeRescalingCompensationConfig",
    "MlpPruningSpec",
    "ModelArtifact",
    "ModelSpec",
    "MultiClusterPhaseAwareMagnitudeRescalingCompensationConfig",
    "MultiplicativeCompensationConfig",
    "PcaCompensationConfig",
    "PhaseAwareCompensationConfig",
    "PhaseAwareLastTokenCompensationConfig",
    "PhaseAwareMagnitudeRescalingCompensationConfig",
    "PositionAwareCompensationConfig",
    "QEffCompileSpec",
    "RemoveLayersSpec",
    "ScaledCompensationConfig",
    "SkipLayersSpec",
    "StructuredSparsitySpec",
    "TransformationPlan",
    "plan_from_dict",
    "plan_to_dict",
    "transform_spec_from_dict",
    "transform_spec_to_dict",
]
